"""add_sprint11_fields_to_rescisao2

Revision ID: 05bc0780607b
Revises: 5f9dd8257224
Create Date: 2026-04-09 12:11:38.151625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bc0780607b'
down_revision: Union[str, Sequence[str], None] = '5f9dd8257224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescisoes', sa.Column('criado_por', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rescisoes', 'usuarios', ['criado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescisoes', type_='foreignkey')
    op.drop_column('rescisoes', 'criado_por')
    # ### end Alembic commands ###
