"""Adicionando tabela de itens de rescisao

Revision ID: 416987c39808
Revises: 670451ac9262
Create Date: 2026-03-13 10:39:33.365110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416987c39808'
down_revision: Union[str, Sequence[str], None] = '670451ac9262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_rescisao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rescisao_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['rescisao_id'], ['rescisoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_rescisao')
    # ### end Alembic commands ###
