"""add_sprint11_fields_to_rescisao

Revision ID: 5f9dd8257224
Revises: b5d63dbedf0b
Create Date: 2026-04-09 11:55:40.279720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9dd8257224'
down_revision: Union[str, Sequence[str], None] = 'b5d63dbedf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescisoes', sa.Column('motivo_saida', sa.String(), nullable=True))
    op.add_column('rescisoes', sa.Column('observacoes_internas', sa.Text(), nullable=True))
    op.add_column('rescisoes', sa.Column('chaves_devolvidas', sa.Boolean(), nullable=True))
    op.add_column('rescisoes', sa.Column('contas_consumo_quitadas', sa.Boolean(), nullable=True))
    op.add_column('rescisoes', sa.Column('controle_portao_devolvido', sa.Boolean(), nullable=True))
    op.add_column('rescisoes', sa.Column('vistorias_concluidas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rescisoes', 'vistorias_concluidas')
    op.drop_column('rescisoes', 'controle_portao_devolvido')
    op.drop_column('rescisoes', 'contas_consumo_quitadas')
    op.drop_column('rescisoes', 'chaves_devolvidas')
    op.drop_column('rescisoes', 'observacoes_internas')
    op.drop_column('rescisoes', 'motivo_saida')
    # ### end Alembic commands ###
