"""Criando tabelas iniciais

Revision ID: 670451ac9262
Revises: 
Create Date: 2026-03-13 10:00:01.935871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670451ac9262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imobiliarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('config_calculo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imobiliarias_cnpj'), 'imobiliarias', ['cnpj'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imobiliaria_id', sa.UUID(), nullable=True),
    sa.Column('locatario_nome', sa.String(), nullable=False),
    sa.Column('valor_aluguel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_iptu', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_condominio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=True),
    sa.Column('multa_total_meses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imobiliaria_id'], ['imobiliarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rescisoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=True),
    sa.Column('data_desocupacao', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rescisoes')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_imobiliarias_cnpj'), table_name='imobiliarias')
    op.drop_table('imobiliarias')
    # ### end Alembic commands ###
