"""add_branding_fields_to_imobiliaria

Revision ID: b5d63dbedf0b
Revises: 62140b2dd48b
Create Date: 2026-03-23 20:49:41.224159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d63dbedf0b'
down_revision: Union[str, Sequence[str], None] = '62140b2dd48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imobiliarias', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('imobiliarias', sa.Column('endereco_completo', sa.String(), nullable=True))
    op.add_column('imobiliarias', sa.Column('telefone_contato', sa.String(), nullable=True))
    op.add_column('imobiliarias', sa.Column('chave_pix', sa.String(), nullable=True))
    op.alter_column('imobiliarias', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imobiliarias', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('imobiliarias', 'chave_pix')
    op.drop_column('imobiliarias', 'telefone_contato')
    op.drop_column('imobiliarias', 'endereco_completo')
    op.drop_column('imobiliarias', 'logo_url')
    # ### end Alembic commands ###
