"""add_auditoria_rescisoes

Revision ID: fda7ee8f843a
Revises: 4206d1aae11d
Create Date: 2026-04-10 14:50:01.175211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda7ee8f843a'
down_revision: Union[str, Sequence[str], None] = '4206d1aae11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescisoes', sa.Column('aprovado_por', sa.UUID(), nullable=True))
    op.add_column('rescisoes', sa.Column('data_aprovacao', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'rescisoes', 'usuarios', ['aprovado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rescisoes', type_='foreignkey')
    op.drop_column('rescisoes', 'data_aprovacao')
    op.drop_column('rescisoes', 'aprovado_por')
    # ### end Alembic commands ###
